name: MyST GitHub Pages Deploy

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  # `BASE_URL` determines, relative to the root of the domain, the URL that your site is served from.
  # E.g., if your site lives at `https://mydomain.org/myproject`, set `BASE_URL=/myproject`.
  # If, instead, your site lives at the root of the domain, at `https://mydomain.org`, set `BASE_URL=''`.
  BASE_URL: /${{ github.event.repository.name }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.9.2
      with:
        cache: true
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

    - name: List installed packages
      run: pixi list

    - name: Build the site
      run: pixi run build

    - name: Upload site
      uses: actions/upload-artifact@v5
      with:
        name: site
        path: 'book/_build/html/'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'

    steps:

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - uses: actions/download-artifact@v6
      with:
        name: site
        path: 'deploy'

    - name: Fix permissions
      run: |
        chmod -c -R +rX "deploy/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: 'deploy'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
